name: Run CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
        
    - name: Install go lint
      run: go install golang.org/x/lint/golint@latest

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1

    - name: Run go lint
      run: |
        golint ./...
    
    - name: Run golangci-lint
      run: |
        golangci-lint run --config=.golangci.yaml --print-issued-lines=false --out-format=colored-line-number --issues-exit-code=0
